<a href="https://colab.research.google.com/github/Fargus8866/Fargus8866/blob/main/first_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import random
arr=np.arange(10,100,10)
arr[3:]



array([40, 50, 60, 70, 80, 90])

In [23]:
arr1=arr[3:6].copy()
arr1

array([40, 50, 60])

In [24]:
arr1[:]=0

In [25]:
arr1

array([0, 0, 0])

In [26]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
arr2d=np.random.randint(1,100,size=(3,3))
arr2d

array([[42, 63, 29],
       [67, 69, 15],
       [99, 11, 38]])

In [29]:
arr2d[2,2]

38

In [30]:
arr22=arr2d[2,0:3]
arr22

array([99, 11, 38])

In [31]:
arrd=np.array
arrd

<function numpy.array>

In [35]:
arrd=np.random.randint(1,100,size=(3,3,3))
arrd

array([[[26, 50, 91],
        [70, 31, 17],
        [ 6, 64, 48]],

       [[56, 86, 39],
        [52, 87, 53],
        [91, 27, 29]],

       [[72, 67, 21],
        [52, 22, 76],
        [69, 62,  6]]])

In [36]:
arrd[0][1,1]

31

In [37]:
arrd[1][2,1]

27

In [38]:
input()

dfgdfgdfg


'dfgdfgdfg'

In [5]:
ismlar=[]
for i in range(3):
  ismlar.append(input("Ism kiriting: >>> "))
arrism=np.array(ismlar)
arrism

Ism kiriting: >>> sdfsdf
Ism kiriting: >>> sdgdfg
Ism kiriting: >>> sdfasd


array(['sdfsdf', 'sdgdfg', 'sdfasd'], dtype='<U6')

In [40]:
date=np.random.randn(6,5)
date

array([[ 0.36122601, -0.12756982, -0.55892913, -0.18198913,  1.60766071],
       [-0.18214693,  1.96168103, -1.21077277,  0.92171138, -0.86889179],
       [-1.78324251,  0.07071176, -1.86193994,  1.53990283, -1.14148519],
       [-0.07439047,  0.21233676, -2.03731805,  0.289961  , -0.92753317],
       [ 1.03723425, -0.02513013,  0.78411867, -0.61331728, -1.04616335],
       [ 0.22618001, -0.57277416,  0.8799807 ,  0.83318726,  0.2991275 ]])

In [42]:
date[arrism!='shix']

array([[ 0.36122601, -0.12756982, -0.55892913, -0.18198913,  1.60766071],
       [-1.78324251,  0.07071176, -1.86193994,  1.53990283, -1.14148519],
       [-0.07439047,  0.21233676, -2.03731805,  0.289961  , -0.92753317],
       [ 1.03723425, -0.02513013,  0.78411867, -0.61331728, -1.04616335],
       [ 0.22618001, -0.57277416,  0.8799807 ,  0.83318726,  0.2991275 ]])

In [66]:
arr8 = np.arange(0, 9).reshape(3, 3)
arr8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arr8[2,:2]

array([6, 7])

In [4]:
arr9=np.array(list(range(27))).reshape(3,3,3)
arr9

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
arr=np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])
arr[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [40]:
arr98=arr[1]
arr98
np.array(arr98[1:,:2])

array([[12, 13],
       [15, 16]])

In [58]:
ismlar=np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
data=np.array([[5, 6, 1, 1],
    [9, 1, 1, 1],
    [7, 7, 4, 2],
    [1, 5, 1, 9],
    [9, 9, 4, 5],
    [7, 5, 9, 6],
    [5, 3, 7, 4]])
mask = (ismlar == 'Javohir') | (ismlar == 'Elyor')
data[mask]
arr2=data[mask].copy()
arr2

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])